= IT Tools
:page-role: home

.Communication
[.def#communication]
****

[.left]
image::slack-icon.svg[width=100px]

--
CSMI uses link:https://slack.com/intl/fr-fr/[Slack] to communicate with promotions and on projects.

You can install slack and create your account with your email `@etu.unistra.fr` once you have it.
You'll receive an invitation at the start of the school year.

The Slack workspace used is that of {feelpp}, the numerical simulation software developed by Cemosis. The channels used are

`#csmi-202x`:: for 202x promotions
`#csmi`:: for questions about the CSMI Master's program

++++
<div class="content">
        <div class="actions">
            <a href="https://join.slack.com/t/feelpp/shared_invite/zt-2qe0q9hw-4pVbhohCXUE6Po9Ma8dbiQ"
                class="button join-chat" style="display: flex; justify-content: center; align-items: center;">
                <span class="icon"><img src="/_/img/slack-icon.svg"></span>
                 <span> Join CSMI Slack Channels</span>
                </a>
        </div>
</div>
++++
--
****

.Operating systems
[.def#systeme]
****
[.grid.has-emblems]
[emblem]#Linux#::  link:https://ubuntu.com/download/desktop/thank-you?version=22.04.1&architecture=amd64[Ubuntu 22.04 LTS] or later, or Debian 11 or later
+
image:en:csmi:img-ubuntu.svg[width=100px] image:en:csmi:img-debian.svg[width=100px]
[emblem]#Windows 1x#:: Install link:https://docs.microsoft.com/fr-fr/windows/wsl/install[WSL support] then use link:https://apps.microsoft.com/store/detail/ubuntu-22041-lts/9PN20MSR04DW?hl=fr-fr&gl=FR[Ubuntu 22.04] or Debian 11 or later
+
image:en:csmi:img-win.svg[width=100px]
[emblem]#MacOs#:: Install link:https://brew.sh/index_fr[Homebrew] that offers a lot of packages either on Intel or ARM processors
+
image:en:csmi:img-macos.svg[width=100px]
****


.programming environment
[.def#programming]
****
We'll be using the following tools in several courses

[.grid.has-emblems]
[emblem]#Programming languages#::
+
image:en:csmi:img-cpp.svg[width=100px] image:en:csmi:img-python.svg[width=100px] 
// image:en:csmi:img-rust.svg[width=100px] image:en:csmi:img-julia.svg[width=100px]
+
Here are the programming languages you'll be using:
+
* - C 
* - C{pp} 
* - Python3
+
and others you may use in your projects
+
* - Rust
* - Julia
+
and use advanced programming environment based on
+
* - CMake

[emblem]#https://code.visualstudio.com/[Visual Studio Code]#:: 
+
image:en:csmi:img-vscode.svg[width=100px]
+
* - connect to remote machines
* - work on one or more projects at a time
* - use git
+
Powerful extensions are available for most programming languages, in particular
+
* - C/C{pp} https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools[extension]
* - Python https://marketplace.visualstudio.com/items?itemName=ms-python.python[extension]
* - CMake https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools[extension]
* - Rust https://marketplace.visualstudio.com/items?itemName=rust-lang.rust[extension]
* - Julia https://marketplace.visualstudio.com/items?itemName=julialang.language-julia[extension]
* - LaTeX https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop[extension]
* - Asciidoc https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode[extension]


[emblem]#https://github.com[Github]#:: 
+
image:en:csmi:img-github.svg[width=100px]
+
The number one platform for open-source projects using git as a version control system, the platform also offers a lot of tools for project management. +
We'll be using https://github.com/features/issues[Github management tools] to keep track of projects and assignments. +
You need to create an account on Github, a form will be sent at the beginning of the M1 year and your account will follow you during the 2 years. It will be used
+
* - for projects in S2 and S3
* - during internships, to submit your reports and presentations
* - during internships for some of you, for follow-up purposes 
* - during EDP (S2) and CS3 courses, via the https://classroom.github.com[github classroom] platform, to hand in your assignments. 
+
One reference: https://lab.github.com/ but there are plenty of others.

****


