= Emplois pour le Master CSMI
:page-role: home
:experimental:

[TIP]
====
- Le réseau est la première modalité pour trouver un emploi. Créer le votre et développer vos contacts.
- Créer un compte sur LinkedIn et autres plateformes de mise en relation pour un emploi.
====

[discrete]
== Forums Emploi 

[.grid.has-emblems]
[.emblem]#Forum Emploi Math#::
La plus grande rencontre étudiants, diplomés et entreprises en France en Mathématiques. Il aura lieu le 11 Octobre 2022 à La Villette, Paris.
btn:[https://www.2022.forum-emploi-maths.com/[> Site Web]]
btn:[https://twitter.com/forumemploimath[> Twitter]] +


[.emblem]#Forum AlsaTech Unistra#::
La plus grande rencontre étudiants, diplômés et entreprises du Grand Est. Il aura lieu les 22 Octobre 2022 à Strasbourg.
btn:[https://forum.alsacetech.unistra.fr/[> Site web]]
btn:[https://www.linkedin.com/company/forum-alsace-tech-unistra/about/[> LinkedIn]] +


[.emblem]#Onisep#::
La brochure sur les métiers des Mathématiques, de la Statistique et de l'Informatique, 2021.
btn:[https://www.onisep.fr/Decouvrir-les-metiers/Des-metiers-qui-recrutent/La-collection-Zoom-sur-les-metiers/Les-metiers-des-mathematiques-de-la-statistique-et-de-l-informatique[> Onisep]]
btn:[https://www.onisep.fr/content/download/769765/14361027/version=3/file/ZOOM-MATHS_partenaires.pdf[> PDF]]


[discrete]
== Portails Emploi

[.grid.has-emblems]
[.emblem]#Stages & Emplois#::
btn:[https://github.com/master-csmi/csmi/discussions/categories/stages-et-emplois/[> CSMI]]

[.emblem]#AMIES/EU-Maths-In#::
btn:[https://jobs.eu-maths-in.eu/jobs[> Portail]]

    
[.emblem]#LinkedIn#::
Il faut créer votre profil sous LinkedIn, c'est un réseau professionel. 
btn:[https://www.linkedin.com/[> LinkedIn]]