:stem: latexmath
:imagesprefix:
:experimental:
ifdef::env-github,env-browser,env-vscode[:imagesprefix:]

= Master CSMI : Calcul Scientifique et Mathématiques de L'Innovation   {master-year}
:navtitle: Home
:page-role: home

[.grid.has-emblems]
[.emblem]#Responsable de la formation#::
Christophe Prud'homme <prudhomme@unistra.fr>

[.emblem]#Responsable administrative#::
Marie-Line Vos <marieline.vos@unistra.fr>

[.grid.has-emblems]
[.emblem]#Discussions#::
https://github.com/master-csmi/csmi/discussions

[.emblem]#Twitter#::
https://twitter.com/master_csmi

[.emblem]#LinkedIn#::
https://www.linkedin.com/company/master-csmi


[.panel]
--
[discrete]
== Objectifs 

La spécialité Calcul Scientifique et Mathématique de l'Innovation -- **CSMI** --  a pour objectif de former des mathématiciens de haut niveau avec une double compétence en mathématiques et en informatique. 
Les aspects théoriques et appliqués sont abordés conjointement tout au long du parcours. 
L'étudiant est confronté à des problématiques industrielles au travers de projets avec des entreprises puis en stages M1 et M2.
--

[.panel]
--
[discrete]
**Master CSMI : Une Formation d'Excellence en IA, HPC, Modélisation, Simulation et Traitement des Données**

Le programme du Master CSMI est une réponse adaptée aux besoins critiques du monde socio-économique actuel. Basé sur des analyses de pointe comme le rapport EISEM de 2015 et l'étude du CNRS de 2022 sur l'impact des mathématiques, notre parcours vise l'excellence en matière d'intelligence artificielle (IA), de calcul haute performance (HPC), de modélisation, de simulation, d'optimisation, ainsi que de traitement de l'image et du signal.

Nos étudiants bénéficient d'une formation approfondie touchant aussi bien les domaines théoriques qu'appliqués de l'algorithmique, du calcul scientifique, des équations aux dérivées partielles, des statistiques, des probabilités, de l'algèbre et de la géométrie. De plus, l'importance capitale de l'informatique dans ces domaines est fortement soulignée, préparant nos étudiants à maîtriser divers langages de programmation, logiciels et plateformes numériques.

Au-delà de l'acquisition de connaissances, notre programme garantit une mise en application concrète grâce à des projets collaboratifs avec des entreprises partenaires. Ainsi, nos diplômés sont non seulement équipés des compétences recherchées mais également prêts à les mettre en œuvre dans un environnement professionnel dynamique.
--

[discrete]
== Admission

[.grid.has-emblems]
[.emblem]#Admission en M1#::
Sur dossier et après avis de la commission pédagogique pour les titulaires d'une licence de Mathématiques ou équivalent.

[.emblem]#Admission en M2#::
- De plein droit pour les titulaires du M1 CSMI.  
- Sur dossier et après avis de la commission pédagogique pour les titulaires d'un M1 équivalent.

[discrete]
== Débouchés

[.grid.has-emblems]
[.emblem]#Services de R&D#::
- La majorité des diplômés s'orientent vers les services de recherche et développement des entreprises (des start-ups aux grands groupes), les sociétés de services et les entreprises de consulting spécialisées ou les postes d'ingénieur dans les universités et les organismes de recherche publics ou privés.

[.emblem]#Doctorat#::
- Les étudiants de la filière les plus motivés par la recherche appliquée pourront également poursuivre en doctorat, en laboratoire ou en entreprise.

