= Stages

== Modalités

Les stages de M2 durent au minimum 4 mois et au maximum 6 mois entre les mois de février et septembre.

Les stages de M1 durent en 6 semaines et 2 mois entre les mois de juin et août.

Les soutenances ont lieu fin août.

1. L'étudiant contacte le responsable de la formation afin de valider le sujet de stage avec une description suffisante 
2. L'étudiant devra remplir ensuite une demande de convention de stage sur l'ENT 
3. Ensuite la convention sera à signer par les différentes parties: étudiant, entreprise, direction de l'UFR,  responsable de stage, responsable de formation.

NOTE: Au delà de 2 mois, le stage doit être rémunéré. 

== Années précédentes

- xref:csmi-stages-2022:ROOT:index.adoc[Stages 2022]
- xref:csmi-stages-2021:ROOT:index.adoc[Stages 2021]

== Rapport de stages

=== Introduction 

=== Plan

==== Objectifs

==== Contexte

==== Contributions

==== Bilan

==== Bibliographie

=== La Forme

==== Orthographe et Grammaire

==== Bibliographie


=== Soutenance

Les soutenances ont lieu fin août, elles permettent à l'étudiant de présenter son travail de manière concise devant un jury de 3 personnes qui assistent à l'ensemble des présentations.

Les présentations durent 30 minutes dont 20 minutes de présentations et 10 minutes de questions.


